// Contiens toutes nos pizzas.
const pizzas = [
    {
        id: 1,
        name: "Raclette",
        img: "https://assets.afcdn.com/recipe/20210519/120398_w1024h768c1cx1060cy707.jpg",
        alt: "Une pizza à la raclette",
        price: 9,
        description: "Crème fraîche légère française, mozzarella, bacon, pommes de terre françaises sautées, oignons, raclette française.",
        ranking: 4,
    },
    {
        id: 2,
        name: "Chèvre-Miel",
        img: "https://www.surlesentierdesbergers.fr/img/cms/idees-recettes/pizza-chevre-miel-truffe/page-recette-pizza-chevre-miel-haut.jpg",
        alt: "Une pizza au chèvre et au miel",
        price: 8,
        description: "Crème fraîche légère française, mozzarella, chèvre, miel français.",
        ranking: 5,
    },
    {
        id: 3,
        name: "Chorizo",
        img: "https://recette.supertoinette.com/151465/b/pizza-au-chorizo.jpg",
        alt: "Une pizza au chorizo",
        price: 9,
        description: "Sauce tomate bio, mozzarella, chorizo français, chèvre, olives Kalamata bio.",
        ranking: 5,
    },
    {
        id: 4,
        name: "Deluxe",
        img: "https://media-cdn.tripadvisor.com/media/photo-s/19/a1/d8/d8/pizza-reblochon-jambon.jpg",
        alt: "Une pizza deluxe",
        price: 7,
        description: "Sauce tomate bio, mozzarella, boulettes de bœuf assaisonnées*, champignons de Paris, oignons, duo de poivrons.",
        ranking: 3,
    },
    {
        id: 5,
        name: "Indienne",
        img: "https://www.cuisineactuelle.fr/imgre/fit/http.3A.2F.2Fprd2-bone-image.2Es3-website-eu-west-1.2Eamazonaws.2Ecom.2Fcac.2F2019.2F10.2F18.2F5396d109-f6de-43ef-af0c-b81a3b340186.2Ejpeg/750x562/quality/80/crop-from/center/cr/wqkgUGFyw6kvU3VjcsOpIHNhbMOpIC8gQ3Vpc2luZSBBY3R1ZWxsZQ%3D%3D/pizza-indienne.jpeg",
        alt: "Une pizza à l'indienne",
        price: 8,
        description: "Crème fraîche légère française, mozzarella, oignons, poulet rôti*, champignons de Paris, emmental français.",
        ranking: 4,
    },
    {
        id: 6,
        name: "Kebab",
        img: "https://www.pate-a-pizza.com/wp-content/uploads/2016/10/pizza-kebab.jpg",
        alt: "Une pizza au kebab",
        price: 6,
        description: "Sauce tomate bio, mozzarella, viande kebab*, oignons, tomates fraîches, sauce samouraï.",
        ranking: 4,
    },
    {
        id: 7,
        name: "Saumon",
        img: "https://www.casa-pizza.com/images/photorecettes/pizza-saumon-frais-123rf.jpg",
        alt: "Une pizza au saumon",
        price: 9,
        description: "Crème fraîche légère française, mozzarella, saumon fumé au bois de hêtre, oignons, pommes de terre françaises sautées.",
        ranking: 5,
    },
    {
        id: 8,
        name: "Forestière",
        img: "https://pizzaplanetkmn.be/wp-content/uploads/2019/03/Pizza-Forestie%CC%80re.jpg",
        alt: "Une pizza forestière",
        price: 7,
        description: "Crème fraîche légère française, mozzarella, lardons fumés, oignons, jambon, champignons de Paris, origan.",
        ranking: 2,
    },
    {
        id: 9,
        name: "Orientale",
        img: "https://i0.wp.com/donatello-and-co.com/wp-content/uploads/2020/09/Orientale-recadre.jpg?fit=1200%2C654&ssl=1",
        alt: "Une pizza orientale",
        price: 10,
        description: "Sauce tomate bio, mozzarella, oignons, merguez*, duo de poivrons.",
        ranking: 3,
    },
    {
        id: 10,
        name: "Steak & Chesse",
        img: "https://thekittchen.com/wp-content/uploads/2016/04/PRE-Brand-Steak-and-Blue-Cheese-Pizza-2.jpg",
        alt: "Une pizza au steak et fromage",
        price: 12,
        description: "Sauce tomate bio, mozzarella, boulettes de bœuf assaisonnées*, tomates fraîches, origan.",
        ranking: 4,
    },
    {
        id: 11,
        name: "Margherita",
        img: "https://assets.afcdn.com/recipe/20181212/84802_w1024h576c1cx2736cy1824.jpg",
        alt: "Une pizza margherita",
        price: 4,
        description: "Sauce tomate bio, mozzarella.",
        ranking: 2,
    },
    {
        id: 12,
        name: "Vegan",
        img: "https://www.veganfreestyle.com/wp-content/uploads/2018/02/pizza-vegan.jpg",
        alt: "Une pizza vegan",
        price: 10,
        description: "Sauce tomate bio, râpé vegan, champignons, oignons, duo de poivrons, olives Kalamata Bio dénoyautées, tomates fraîches, origan.",
        ranking: 3,
    },
]

export default pizzas;
